*******************************************************************************
****** decoder schematic ECE482final_cadence  <vs>  decoder layout ECE482final_cadence
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(txgate schematic ECE482final_cadence, _) Cell            2       0*
(g45n1svt) MOS                                    0       2*
(g45p1svt) MOS                                    0       2*
                                             ------  ------
Total                                             2       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    2       2           2       2
(g45p1svt) MOS                                    2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

Schematic and Layout Match
