*******************************************************************************
****** schmitt_buff_1_8V schematic ECE482final_cadence  <vs>  schmitt_buff_1_8V layout ECE482final_cadence
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p2svt) MOS                                    4       4
(g45n2svt) MOS                                    4       4
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n2svt) MOS                                    4       4           4       4
(g45p2svt) MOS                                    4       4           4       4
                                             ------  ------      ------  ------
Total                                             8       8           8       8

*******************************************************************************
****** lvl_shifter_iotoc schematic ECE482final_cadence  <vs>  lvl_shifter_iotoc layout ECE482final_cadence
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    2       2
(g45n2svt) MOS                                    3       3
(g45p2svt) MOS                                    1       1
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n2svt) MOS                                    3       3           3       3
(g45p1svt) MOS                                    2       2           2       2
(g45p2svt) MOS                                    1       1           1       1
                                             ------  ------      ------  ------
Total                                             6       6           6       6

*******************************************************************************
****** EN_IO schematic ECE482final_cadence  <vs>  EN_IO layout ECE482final_cadence
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(schmitt_buff_1_8V schematic ECE482final_cadence, schmitt_buff_1_8V) Cell               1       1
(lvl_shifter_iotoc schematic ECE482final_cadence, lvl_shifter_iotoc) Cell               1       1
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(lvl_shifter_iotoc) Cell                          1       1           1       1
(schmitt_buff_1_8V) Cell                          1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

Schematic and Layout Match
