*******************************************************************************
****** lvl_shifter_iotoc schematic ECE482final_cadence  <vs>  lvl_shifter_iotoc layout ECE482final_cadence
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    2       2
(g45n2svt) MOS                                    3       3
(g45p2svt) MOS                                    1       1
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n2svt) MOS                                    3       3           3       3
(g45p1svt) MOS                                    2       2           2       2
(g45p2svt) MOS                                    1       1           1       1
                                             ------  ------      ------  ------
Total                                             6       6           6       6

Schematic and Layout Match
